### ISSUE TITLE
Adding to Box instructions on README

### ISSUE THREAD

**Issue by KristinaRiemer** [UArizonaGSICampusLivingLab/gsi-wrangling-workflow#13]
- add note about how to get access to box app 
    - add as collaborator
    - Can go to Box console here: https://arizona.app.box.com/developers/console
- clarity about how to run data wrangling script locally compared to the automated Posit Connect version

**Comment by Aariq** [comment]
The link to the box developers console is right at the top of the section of the `boxr` docs I linked to, so I'd rather not repeat that, but I'll see if I can clarify things a bit.

**Comment by Aariq** [comment]
Clarified a bit in 280e6965b054248557b6eb74ff671ff3ad351a3e
