### ISSUE TITLE
Provide site info, metadata, and example scripts alongside data

### ISSUE THREAD

**Issue by Aariq** [UArizonaGSICampusLivingLab/gsi-wrangling-workflow#14]
In the Box folder alongside the versioned data we should include:

- [x] The information about sites and locations of the sensors (currently in metadata.csv, but maybe re-named something like "site_info.csv") (@MJBarrios)
- [x] Metadata—e.g. units for numeric, that observations were recorded in AZ but datetime is displayed in standard UTC time, etc. (@MJBarrios, @UArizonaCampusLivingLabforGSI)
- [ ] Citation info
- [ ] R script (& python script?) for reading in data and wrangling datetime column (@Aariq)

**Comment by Aariq** [comment]
I just dropped `site_info.csv` in the Box folder, FYI

**Comment by UArizonaCampusLivingLabforGSI** [comment]
I added GSI-METADATA.doc into the Box folder.

**Comment by Aariq** [comment]
Awesome.  I'm going to close this issue for now.  We can re-visit the idea of putting an example R script in the box folder later
