### ISSUE TITLE
Create separate API key for dashboard

### ISSUE THREAD

**Issue by Aariq** [UArizonaGSICampusLivingLab/gsi-wrangling-workflow#16]
I think ideally there should probably be a separate API key for interactive use, the data wrangling workflow, and the Shiny app.  Should look into it with Zentra Cloud

**Comment by Aariq** [comment]
@UArizonaCampusLivingLabforGSI talked to the Zentra Cloud team and they recommended doing this, partly because changing the units on the portal *does* change the units for the data downloaded from the API.  We want to avoid having this change.

**Comment by UArizonaCampusLivingLabforGSI** [comment]
I have started creating the new API and would like to change it to a push. This change requires the Endpoint URL. I assume this will be the Box but wanted to double-check that this would be the correct location. I can always make it to test and update if it is wrong. @Aariq do you have insight here?

**Comment by Aariq** [comment]
I'm not sure we can make use of the Push API—I haven't found any information about how to use push APIs with R.  I suppose if we did use it, it would be for the shiny app, so maybe the endpoint URL is the shiny app?  Will the new API token also allow access to the REST API?

**Comment by UArizonaCampusLivingLabforGSI** [comment]
I am not sure, they may be different and as you have mentioned maybe it is not the correct route to change that feature. I will do a bit more digging today and see if there is a clear use or if it makes sense to continue using the REST API only.

**Comment by Aariq** [comment]
For the Push API it sounds like there needs to be a server running at that Endpoint to accept the "payload".  There is a server running when someone is accessing the Shiny app, but I don't know how to configure it to accept a payload from a Push API.  The current data wrangling workflow doesn't use a server that could accept data from a push API.

**Comment by UArizonaCampusLivingLabforGSI** [comment]
Separate API token is updated in the secret and the old token is still there as a note in case we need it for any reason in the meantime.

I will confirm units today to make sure they are the same between accounts.
