### ISSUE TITLE
Get calculated variables from REST API

### ISSUE THREAD

**Issue by Aariq** [UArizonaGSICampusLivingLab/gsi-wrangling-workflow#23]
Zentracloud has an API endpoint for calculated variables like plant-available water and evapotranspiration.  Need to access this and add to our dataset.

**Comment by UArizonaCampusLivingLabforGSI** [comment]
Instructions on how to get environmental variables directly from zentra using the API can be found here:
https://zentracloud.com/api/v3/documentation/ 

This documents using a PUSH API
https://docs.zentracloud.com/l/en/article/39tw3ctj9n-api-endpoint
